---
title: "Remote 1-on-1 meetings"
date: "2020-11-04T09:10:38Z"
draft: false
description: "Some things I learned while doing remote 1-on-1 meetings"
tags:
  - people
  - management
---

In the last two years I've done hundreds of remote 1-on-1 meetings, both
as a contributor talking to my manager(s) and as a manager talking to
people in my team.

As a manager, I consider 1-on-1 meetings the most important
responsibility I have: empowering other people to do their best work can
greatly outmeasure any contribution I can give on my own.

What follows is some notes on what seems to work for me. It does not
represent by any means a proper research on the matter, so please take
it with a grain of salt.

** Long term objectives
   :PROPERTIES:
   :CUSTOM_ID: long-term-objectives
   :END:

Regular 1-on-1 meetings can certainly be used to solve immediate,
short-term blockers or clarify some questions, but the long term
objective is building a working professional relationship where:

- Both parties can safely be vulnerable and address deep issues that
  make day to day work more difficult. This can be anything from anxiety
  about the world at large, to having to homeschool kids, to
  difficulties in multitasking different responsibilities. Note that as
  a manager, you're allowed to show that you're struggling to the other
  person. We're human after all and that helps building transparent
  relationships. Needless to say, confidentiality and respect are
  paramount.
- Trust takes time and effort. It may take months before people open up
  and start addressing important topics: what motivates them, problems
  they see in the team and in the company, their own aspirations and
  ultimately work on their professional growth.
- Lead by example: if you ask a complex question (e.g. what do you wanna
  focus on this year?), answer it yourself first, so that they
  understand better.
- Always prepare something to talk about: even if it seems artificial,
  it will gradually tune your perception to be on the lookout between
  meetings for topics to talk about and it will get easier. At the same
  time, if the other party doesn't provide topics over multiple
  meetings, make sure you address that. There's always something to talk
  about.

** Preparation
   :PROPERTIES:
   :CUSTOM_ID: preparation
   :END:

Regular 1-on-1 meetings require preparation: the easiest thing to do to
ease preparation is to keep an agenda document shared between the two
participants.

I can recommend a shared Google Doc, with sections titled by date and
sorted in reverse chronological order (most recent first).

This way you can:

1. Predictably add topics to discuss between meetings (it's always at
   the top).
2. Have implicit time tracking, i.e. you know when something was
   discussed.
3. Easily collaborate in real time during the meeting to capture ideas
   in a form that correctly reflects the other person's thoughts.

This system is by no means perfect (especially if you end up having
dozens of these documents), but it's flexible enough that you can adapt
it to individual preferences. For example, I find that with some people
we can use the agenda to discuss topic asynchronously in writing
beforehand (and draw some conclusions in the meeting), while with other
we defer discussion to the meeting itself. With other ones, we end up
adding topics during the meeting as the conversation naturally goes in
different directions.

In addition, it's important to prepare for the conversation, even for
just 5-10 minutes before the meeting. Having such time buffer not only
helps clarifying thoughts beforehand, but also gives you an opportunity
to stop thinking about what you were doing before and what you're gonna
be doing after the meeting.

** During the meeting
   :PROPERTIES:
   :CUSTOM_ID: during-the-meeting
   :END:

1. Respect the agenda as much as you can, making sure that you either
   address all points on it or explicitly say "We'll need to address
   this in a separate call. Can it wait our next planned session or do
   you wanna schedule an earlier follow-up?".
2. If the conversation drifts to a completely different direction and
   time is running tight, make sure both parties are happy to discuss
   that direction at the expense of other topics. You always have the
   option to capture the new topic and address it at a later stage.
3. Be at ease in saying "I don't know, but here's how I plan to find
   out and here's when I'm gonna report back about it". At the end of
   the day, trust is built on transparency and predictability.
4. When the other person explains something to you and you wanna make
   sure you got it right, repeat it back and ask for confirmation. By
   doing that, you both check your understanding and implicitly ask the
   other person to check their own explanation. I've used this
   technique in all sorts of other conversations in my professional and
   personal life and it does absolute wonders in clarifying
   expectations on both sides.
5. If you take notes, learn how to do that quickly by using keywords,
   then fill in the blanks later (and ask for confirmation to the other
   person once done). Writing can break the flow of the conversation,
   so it needs to be done carefully in order to minimize its impact.
6. If a conversation topic implies someone taking an action, explicitly
   state that in the form of "I will" or "You will" or "Someone else
   will", with an indication of when that would happen.
7. If the meeting resulted in some actions, recap them at the end of
   the call.
8. Video conversations have a different pace - let people speak, listen
   carefully, slow down, repeat a few times if needed.
9. Explicitly ask the other person if they think a topic has been
   exhausted before moving on.
10. Respectfully ask the other person how they're doing, leaving them
    space to decide what they can comfortably share with you. Do no pry
    and always qualify your questions with the reason why you're asking
    them. For example, I've been recently asking people how they're
    dealing with the COVID-19 pandemic, because I noticed erratic
    working patterns that suggest they may be working too much (for many
    people, work is much simpler to deal with, so they end up using it
    as a safe haven - I'm not a psychologist though so this is another
    thing to take with a grain of salt).
11. Provide context: while this is important in any company, I believe it's fundamental
    in a remote company because people have more limited opportunities to gather
    context by casually taking part to unscheduled conversations. So if I'm
    discussing a specific project that I think it's connected to other projects,
    I'll share that. More often than not, the person on the other end will
    appreciate the additional information and will make good use of it.

** After the meeting
   :PROPERTIES:
   :CUSTOM_ID: after-the-meeting
   :END:

If you have any action, just do it as early as possible. Your ability to
follow up is by far the most important factor in building trust. If the
other person asks you to do something, you agree to it and you don't,
they will not ask you again.

If at any point you realize you didn't do something you promised to do,
acknowledge your shortcoming, apologize and make up for it. It happens,
and if you're transparent about it usually the other person will
understand.

** Topics
   :PROPERTIES:
   :CUSTOM_ID: topics
   :END:

1-on-1 meetings are structured around the people involved: while you can
definitely start from some guideline questions, they should over time
develop into a unique conversation.

That said, over the course of multiple meetings you should aim at:

- Unblocking specific issue related to current streams of work,
  e.g. "I'm undecided on how to build X, if using this or that."
- Clarify responsibilities, e.g. "Yes, you need to take care of X, while
  Alice can take care of Y."
- Provide feedback on work done, e.g. "I really liked how you did X
  because..." or "I'd like to speak about Y, as there's an opportunity
  to improve Z."
- Useful things to learn about, e.g. "As you're working on X, you might
  enjoy learning about Y."
- Connect the dots with other projects, e.g. "As you're working on X,
  you might be interested to speak to Alice, as she's working on Y,
  which is related to X as..."
- Happiness, satisfaction, and future work e.g. "If we look at the
  roadmap, there's X, Y, Z. Do they interest you? Which one would be
  your initial preference to work on?"

One important aspect is balance: too often 1-on-1 meetings are focused on the
day to day work and don't cover the larger picture. This is why there should be
scheduled Feedback Sessions where you go through some meta-questions that allow
expanding scope.

These are some examples of questions useful for those sessions:

1. Are you happy about the work you're doing? Is it satisfactory?
2. Looking at X time period, can you point out a piece of your work you're proud of?
3. Looking at the same time period, can you point out 3 team
   achievements you're proud of?
4. What should the team focus on in this quarter?
5. If you had a magic wand and could instantly change anything in the
   team, what would that be?

In general, Feedback Sessions are an opportunity to look at the larger picture
and think about the future. For more inspiration, you can consult the [[https://help.small-improvements.com/article/264-24-questions-to-ask-in-your-next-11-meeting][Small
Improvements guide to 1-on-1 meetings]].

** Conclusions
   :PROPERTIES:
   :CUSTOM_ID: conclusions
   :END:

As mentioned before, this is by no means an exhaustive guide, but a collection
on thoughts based on my experience. At the end of the day, if you always focus
on listening to the other person and acting swiftly on their feedback, you will
get good results.
